config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root 'home#welcome'
  get '/404', to: 'application#not_found'

  # session
  resources :sessions, only: %i[new create destroy]
  get 'login_verify', to: 'sessions#confirm_email'
  get 'resend_verification_link', to: 'sessions#getting_resend_verification_link'
  post 'resend_verification_link', to: 'sessions#resend_verification_link'

  # fogot_password
  get 'password_forget', to: 'password#new'
  post 'password_reset_link', to: 'password#reset_link'
  get 'password_reset', to: 'password#password_reset'
  post 'password_update', to: 'password#update'

  # user
  resources :users
  patch 'make_admin', to: 'users#make_admin'

  # city
  resources :cities

  # brand
  resources :brands, only: %i[index create update destroy]

  # car_model
  resources :car_models, only: %i[index create update destroy]

  # dashboard
  get 'admin_dashboard', to: 'dashboard#admin_dashboard'

  # branch
  resources :branches
  get 'find_nearest_branches', to: 'branches#all_branches'
  post 'getlocation', to: 'branches#getlocation'

  # car
  resources :cars, only: %i[new create index show]
  get 'set_car_condition', to: 'cars#set_condition'
  post 'set_car_condition/verify', to: 'cars#verify'

  # searching
  get 'search_cars', to: 'cars#search'
  # get 'filter_cars', to: 'cars#filter'

  # appointment
  post 'cars/inspection_request', to: 'appointment#request_from_seller'
  post 'buyer_dashboard/inspection_request', to: 'appointment#request_from_buyer'
  get 'appointments', to: 'appointment#all_appointments'
  get 'appointments/verification', to: 'appointment#all_appointments_in_admin_dashboard'
  post 'appointments/status_update/:id', to: 'appointment#status_update'
  get 'appointments/buyers_list/:id', to: 'appointment#buyers_list'
  post 'appointment/buyers_list/final_sell/:id/:sell_appointment', to: 'appointment#final_sell'
  post 'markread', to: 'appointment#markread'
  get 'find_status', to: 'appointment#status_check'
  post 'find_status', to: 'appointment#find_status'

  # filteration
  get 'appointment_filter', to: 'filteration#appointment_filter'
  get 'car_filter', to: 'filteration#car_filter'
  get 'filter_and_sort_general_user_appointment', to: 'filteration#filter_and_sort_general_user_appointment'

  match '*unmatched', to: 'application#not_found', layout: false, via: :all, constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage' # Exclude Active Storage routes
  }
end
# rubocop:enable Metrics/BlockLength

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

# Dashboard controller
class DashboardController < ApplicationController
  before_action :require_user
  before_action :require_admin, only: [:admin_dashboard]
  before_action :require_buyer, only: [:buyer_dashboard]
  before_action :require_seller, only: [:cars]
  def buyer_dashboard; end

  def cars
    @car = Car.all
  end

  def admin_dashboard; end
end

app/views/dashboard/_sidebar.html.erb
<div class="d-flex flex-column flex-grow-1 p-3 bg-light" style="width: 280px;height: 84vh;">
  <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
    <span class="fs-4">Admin Dashboard</span>
  </a>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%=link_to "Users",users_path , class:"hover-effect nav-link link-dark #{"active" if (@active_window=="users")}" %>
    </li>
    <li>
      <%=link_to "City",cities_path , class:"hover-effect nav-link link-dark #{"active" if (@active_window=="city")}" %>
    </li>
    <li>
      <%=link_to "Brands",brands_path, class:"hover-effect nav-link link-dark #{"active" if (@active_window=="brands")}"%>
    </li>
    <li>
      <%=link_to "Model",car_models_path , class:"hover-effect nav-link link-dark #{"active" if (@active_window=="model")}" %>
    </li>
    <li>
      <%=link_to "Appointment",appointments_verification_path , class:"hover-effect nav-link link-dark #{"active" if (@active_window=="appointment")}" %>
    </li>
    <li>
      <%=link_to "Set Price",set_car_condition_path , class:"hover-effect nav-link link-dark #{"active" if (@active_window=="car-condition")}" %>
    </li>
    <li>
      <%=link_to "Branches",branches_path , class:"hover-effect nav-link link-dark #{"active" if (@active_window=="branches")}"%>
    </li>
  </ul>
  <hr>
  <div class="dropdown">
    <a href="#" class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
      <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle me-2">
      <strong><%=current_user.name%></strong>
    </a>
    <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser2">
      <li><%=link_to "Profile",user_path(session[:user_id]),class:"dropdown-item"%></li>
      <li><%=link_to "Update Info",edit_user_path(session[:user_id]),class:"dropdown-item"%></li>
      <li><hr class="dropdown-divider"></li>
      <li><%= button_to "Logout", session_path(session[:user_id]), class: "dropdown-item", method: :delete %></li>
    </ul>
  </div>
</div>

app/views/dashboard/admin_dashboard.html.erb
<%=render 'dashboard/sidebar'%>

app/views/dashboard/seller_dashboard.html.erb
<div class="container">
  <div class="row mt-5">
<% @car.each do |car| %>
  <% if car.user_id == session[:user_id] %>
    <div class="card me-3 ms-3 mb-4" style="width: 18rem;background-color: #eee;">
      <%= image_tag car.image ,class:"card-img-top pt-2 img-fluid"%>
      <div class="card-body">
        <h5 class="card-title"> <%= car.brand.name %> <%= car.car_model.name %> </h5>
        <h6 class="card-title"> Reg no: <%= car.reg_no %></h6>
        <p class="card-text"> <%= car.variant %> <br> <%= car.kilometer_driven %> kms</p>
        <p class="card-text"> Price: <%= car.price.present? ? car.price : "yet to update" %> </p>
        <p class="card-text"> Condition: <%= car.condition.present? ? car.condition : "yet to update" %> </p>
        <p> Available at: <br> <%= car.branch.name %> <br> <%= car.branch.city.name %> </p>
        <div class="d-flex flex-column">
          <a type="button" class="btn btn-primary flex-fill mb-1" target="blank" data-mdb-ripple-color="dark" href="/cars/<%= car.id %>">
            view
          </a>
          <% if car.selling_appointment_status.present? %>
            <button type="button" class="btn btn-danger flex-fill" disabled>Appointment booked</button>
          <% else %>
            <button type="button" class="btn btn-danger flex-fill myModalBtn" data-car-id="<%= car.id %>">Book appointment</button>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

  </div>
</div>

<%# Modal %>
<%= render 'cars/appointment_booking_modal'%>

<!-- JS -->
<%= javascript_pack_tag 'cars', 'data-turbolinks-track': 'reload' %>