config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root 'home#welcome'
  get '/404', to: 'application#not_found'

  # session
  resources :sessions, only: %i[new create destroy]
  get 'login_verify', to: 'sessions#confirm_email'
  get 'resend_verification_link', to: 'sessions#getting_resend_verification_link'
  post 'resend_verification_link', to: 'sessions#resend_verification_link'

  # fogot_password
  get 'password_forget', to: 'password#new'
  post 'password_reset_link', to: 'password#reset_link'
  get 'password_reset', to: 'password#password_reset'
  post 'password_update', to: 'password#update'

  # user
  resources :users
  patch 'make_admin', to: 'users#make_admin'

  # city
  resources :cities

  # brand
  resources :brands, only: %i[index create update destroy]

  # car_model
  resources :car_models, only: %i[index create update destroy]

  # dashboard
  get 'admin_dashboard', to: 'dashboard#admin_dashboard'

  # branch
  resources :branches
  get 'find_nearest_branches', to: 'branches#all_branches'
  post 'getlocation', to: 'branches#getlocation'

  # car
  resources :cars, only: %i[new create index show]
  get 'set_car_condition', to: 'cars#set_condition'
  post 'set_car_condition/verify', to: 'cars#verify'

  # searching
  get 'search_cars', to: 'cars#search'
  # get 'filter_cars', to: 'cars#filter'

  # appointment
  post 'cars/inspection_request', to: 'appointment#request_from_seller'
  post 'buyer_dashboard/inspection_request', to: 'appointment#request_from_buyer'
  get 'appointments', to: 'appointment#all_appointments'
  get 'appointments/verification', to: 'appointment#all_appointments_in_admin_dashboard'
  post 'appointments/status_update/:id', to: 'appointment#status_update'
  get 'appointments/buyers_list/:id', to: 'appointment#buyers_list'
  post 'appointment/buyers_list/final_sell/:id/:sell_appointment', to: 'appointment#final_sell'
  post 'markread', to: 'appointment#markread'
  get 'find_status', to: 'appointment#status_check'
  post 'find_status', to: 'appointment#find_status'

  # filteration
  get 'appointment_filter', to: 'filteration#appointment_filter'
  get 'car_filter', to: 'filteration#car_filter'
  get 'filter_and_sort_general_user_appointment', to: 'filteration#filter_and_sort_general_user_appointment'

  match '*unmatched', to: 'application#not_found', layout: false, via: :all, constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage' # Exclude Active Storage routes
  }
end
# rubocop:enable Metrics/BlockLength

app/models/branch.rb
# frozen_string_literal: true

# Branch Model
class Branch < ApplicationRecord
  belongs_to :city
  has_many :cars, dependent: :destroy

  validates :name, :address, :longitude, :latitude, :city_id, :map_link, presence: true

  geocoded_by :address

  after_validation :geocode, if: :address_changed?
end

app/controllers/branch_controller.rb
# frozen_string_literal: true

# Branch controller
class BranchController < ApplicationController
  include BranchHelper
  before_action :require_user
  before_action :require_admin, only: %i[index create edit update]
  def index
    @active_window = 'branches'
    @branch = Branch.all
    @city = City.all
  end

  def show
    @branch = Branch.find(params[:id])
    @city = City.find_by(id: @branch.city_id)
  end

  def create
    getting_values_from_params_for_branch
    @branch = Branch.create(city_id: @city, name: @name,
                            address: @address, map_link: @map_link, latitude: @latitude, longitude: @longitude)
    selected_city_name = City.find_by(id: params[:selected_city])&.name
    render json: { city_name: selected_city_name }
  end

  def edit
    @branch = Branch.find(params[:id])
    @cities = City.all
  end

  def update
    @cities = City.all
    @branch = Branch.find(params[:id])
    if @branch.update(branch_update_params)
      flash[:success] = 'Branch updated successfully'
      redirect_to branch_details_path(@branch)
    else
      # flash.now[:success] = 'now - in same page'
      # flash[:success] = 'diff page'

      # binding.pry

      render action: :edit
    end
  end

  def view_branch
    @branch = Branch.all
    @city = City.all
  end

  def getlocation
    getting_location_from_params_and_find_in_geocoder
    @count = 0
    @render_template = true
    if @results.blank?
      handle_blank_result
      return
    end
    calculate_coordinates(@results)
    @nearest_branches = @sorted_branches.first(5).map { |bw| bw[:branch] }
    @nearest_distances = @sorted_branches.first(5).map { |bw| bw[:distance] }
  end

  private

  def haversine_distance(user_lat, user_lng, branch_lat, branch_lng)
    earth_radius = 6371
    user_lat_rad = to_rad(user_lat)
    user_lng_rad = to_rad(user_lng)
    branch_lat_rad = to_rad(branch_lat)
    branch_lng_rad = to_rad(branch_lng)
    delta_lat = branch_lat_rad - user_lat_rad
    delta_lng = branch_lng_rad - user_lng_rad
    a = calculate_a(delta_lat, user_lat_rad, branch_lat_rad, delta_lng)
    c = calculate_c(a)
    earth_radius * c
  end

  def getting_values_from_params_for_branch
    @city = params[:selected_city]
    @name = params[:selected_branch]
    @address = params[:selected_address]
    @map_link = params[:selected_map]
    @latitude = params[:selected_lat]
    @longitude = params[:selected_long]
  end

  def getting_location_from_params_and_find_in_geocoder
    @place = params[:place]
    @results = Geocoder.search(@place)
  end

  def calculate_coordinates(results)
    coordinates = results.first.coordinates
    @user_lng = coordinates[1]
    @user_lat = coordinates[0]
    calculate_distance(@user_lat, @user_lng)
  end

  def calculate_distance(user_lat, user_lng)
    branches = Branch.all.to_a
    @branches_with_distances = branches.map do |branch|
      branch_lng = branch.longitude.to_f
      branch_lat = branch.latitude.to_f
      distance = haversine_distance(user_lat, user_lng, branch_lat, branch_lng)
      { branch:, distance: }
    end
    @sorted_branches = @branches_with_distances.sort_by { |bw| bw[:distance] }
  end

  def handle_blank_result
    flash.now[:danger] = 'Enter a popular town/city'
    @render_template = false
  end
end

app/controllers/branches_controller.rb
# frozen_string_literal: true

# Branch controller
class BranchesController < ApplicationController
  include BranchHelper
  before_action :require_user
  before_action :require_admin, only: %i[index create edit update]
  def index
    @active_window = 'branches'
    @branch = Branch.all
    @city = City.all
  end

  def show
    @branch = Branch.find(params[:id])
    @city = City.find_by(id: @branch.city_id)
  end

  def create
    getting_values_from_params_for_branch
    @branch = Branch.create(city_id: @city, name: @name,
                            address: @address, map_link: @map_link, latitude: @latitude, longitude: @longitude)
    selected_city_name = City.find_by(id: params[:selected_city])&.name
    render json: { city_name: selected_city_name }
  end

  def edit
    find_branch_from_params
    @cities = City.all
  end

  def update
    @cities = City.all
    @branch = Branch.find(params[:id])
    if @branch.update(branch_update_params)
      flash[:success] = 'Branch updated successfully'
      redirect_to branches_path(@branch)
    else
      render action: :edit
    end
  end

  def destroy
    find_branch_from_params
    if associated_data_present?
      flash[:warning] = 'Failed to delete this branch. This branch has associated cars, delete those first.'
      redirect_to branches_path
      nil
    else
      perform_branch_delete
    end
  end

  def all_branches
    @branch = Branch.all
    @city = City.all
  end

  def getlocation
    getting_location_from_params_and_find_in_geocoder
    @count = 0
    @render_template = true
    if @results.blank?
      handle_blank_result
      return
    end
    calculate_coordinates(@results)
    @nearest_branches = @sorted_branches.first(5).map { |bw| bw[:branch] }
    @nearest_distances = @sorted_branches.first(5).map { |bw| bw[:distance] }
  end

  private

  def haversine_distance(user_lat, user_lng, branch_lat, branch_lng)
    earth_radius = 6371
    user_lat_rad = to_rad(user_lat)
    user_lng_rad = to_rad(user_lng)
    branch_lat_rad = to_rad(branch_lat)
    branch_lng_rad = to_rad(branch_lng)
    delta_lat = branch_lat_rad - user_lat_rad
    delta_lng = branch_lng_rad - user_lng_rad
    a = calculate_a(delta_lat, user_lat_rad, branch_lat_rad, delta_lng)
    c = calculate_c(a)
    earth_radius * c
  end

  def calculate_coordinates(results)
    coordinates = results.first.coordinates
    @user_lng = coordinates[1]
    @user_lat = coordinates[0]
    calculate_distance(@user_lat, @user_lng)
  end

  def calculate_distance(user_lat, user_lng)
    branches = Branch.all.to_a
    @branches_with_distances = branches.map do |branch|
      branch_lng = branch.longitude.to_f
      branch_lat = branch.latitude.to_f
      distance = haversine_distance(user_lat, user_lng, branch_lat, branch_lng)
      { branch:, distance: }
    end
    @sorted_branches = @branches_with_distances.sort_by { |bw| bw[:distance] }
  end
end

app/helpers/branch_helper.rb
# frozen_string_literal: true

# Branch helper
module BranchHelper
  def associated_data_present?
    @branch.cars.present?
  end

  def perform_branch_delete
    flash[:danger] = if @branch.destroy
                       'Branch has been deleted successfully'
                     else
                       'Error deleting this branch'
                     end
    redirect_to branches_path
  end

  def to_rad(degrees)
    degrees * Math::PI / 180
  end

  def calculate_a(delta_lat, user_lat_rad, branch_lat_rad, delta_lng)
    Math.sin(delta_lat / 2)**2 + Math.cos(user_lat_rad) * Math.cos(branch_lat_rad) * Math.sin(delta_lng / 2)**2
  end

  def calculate_c(atan)
    2 * Math.atan2(Math.sqrt(atan), Math.sqrt(1 - atan))
  end

  def branch_update_params
    params.require(:branch).permit(:city_id, :name, :address, :map_link, :latitude, :longitude)
  end

  def find_branch_from_params
    @branch = Branch.find(params[:id])
  end

  def getting_values_from_params_for_branch
    @city = params[:selected_city]
    @name = params[:selected_branch]
    @address = params[:selected_address]
    @map_link = params[:selected_map]
    @latitude = params[:selected_lat]
    @longitude = params[:selected_long]
  end

  def getting_location_from_params_and_find_in_geocoder
    @place = params[:place]
    @results = Geocoder.search(@place)
  end

  def handle_blank_result
    flash.now[:danger] = 'Enter a popular town/city'
    @render_template = false
  end
end

app/views/branches/all_branches.html.erb
<% if session[:role] == 'buyer'%>
  <%= link_to  "Back", cars_path ,class: "ms-2 mt-2"%>
<%end%>
<% if session[:role] == 'seller'%>
  <%= link_to  "Back", cars_path ,class: "ms-2 mt-2"%>
<%end%>
<%if session[:role] != 'admin'%>
  <div class="container">
    <div class="row mt-4">
      <div class="col-md-5    ">
        <%= render partial:"shared/branch"%>
      </div>
      <div class="col-md-5 ms-5">
        <label class="mb-3 h6">Enter your city/landmark/location/pin code and find nearest branch</label>
        <%= form_with url: getlocation_path, method: :post do |form| %>
          <%= form.text_field :place, value: params[:place], class: "form-control",style:"width:15vw;",required: true %>
          <%= form.submit "submit" ,class: "btn btn-primary mt-2"%>
        <% end %>
      </div>
    </div>
  </div>
<%else%>
  <%flash[:danger] = "You are not authorized to access this url"%>
<%end%>

app/views/branches/edit.html.erb
<%= form_with model: @branch, url: branch_path(@branch), method: :patch, class: 'your-form-class' do |form| %>
<section class="vh-70 mt-4">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                <p class="text-center h1 fw-bold mb-2 mx-1 mx-md-4 mt-2">Edit Branch</p>
                <form class="mx-1 mx-md-4">
                  <div class="mb-3">
                    <br>
                    <label for="city-select" class="form-label">Select City:</label>
                    <%= form.select :city_id,  options_for_select(@cities.map { |city| [city.name, city.id] }), { prompt: 'Select City' }, class: 'form-select' %>
                  </div>
                                      <%@branch.errors.full_messages_for(:city_id).each do |message|%>
                      <p class="text-danger"> <%=message%> </p>
                    <%end%>
                  <div class="mb-3">
                    <%= form.label :name, class: 'form-label' %>
                    <%= form.text_field :name, class: 'form-control required', placeholder: 'Branch name' %>
                  </div>
                                      <%@branch.errors.full_messages_for(:name).each do |message|%>
                      <p class="text-danger"> <%=message%> </p>
                    <%end%>
                  <div class="mb-3">
                    <%= form.label :address, class: 'form-label' %>
                    <%= form.text_field :address, class: 'form-control required', placeholder: 'Mention locality, road, landmark, pin' %>
                  </div>
                                      <%@branch.errors.full_messages_for(:address).each do |message|%>
                      <p class="text-danger"> <%=message%> </p>
                    <%end%>
                  <div class="mb-3">
                    <%= form.label :map_link, class: 'form-label' %>
                    <%= form.text_field :map_link, class: 'form-control required', placeholder: 'Map link' %>
                  </div>
                                      <%@branch.errors.full_messages_for(:map_link).each do |message|%>
                      <p class="text-danger"> <%=message%> </p>
                    <%end%>
                  <div class="mb-3">
                    <%= form.label :latitude, class: 'form-label' %>
                    <%= form.text_field :latitude, class: 'form-control required', placeholder: 'Latitude of branch, ex: 2.3522219' %>
                  </div>
                                      <%@branch.errors.full_messages_for(:latitude).each do |message|%>
                      <p class="text-danger"> <%=message%> </p>
                    <%end%>
                  <div class="mb-3">
                    <%= form.label :longitude, class: 'form-label' %>
                    <%= form.text_field :longitude, class: 'form-control required', placeholder: 'Longitude of branch, ex: 48.856614' %>
                  </div>
                                      <%@branch.errors.full_messages_for(:longitude).each do |message|%>
                      <p class="text-danger"> <%=message%> </p>
                    <%end%>
                  <%= form.button 'Update Branch', class: 'btn btn-primary', id: 'add-branch-btn' %>
                </form>
              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2 flex-column">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/branches/getlocation.html.erb
<div class="container">
  <%= link_to "Back", find_nearest_branches_path %>
  <div class="row">
    <p class="h4 text-center mt-3 mb-3">Your search result for the nearest branch of: <span class="text-success"> <%=@place%> </span> </p>
    <% if @render_template == true %>
      <table class="table text-center">
        <thead>
          <tr class="table-active">
            <th>Sl. no</th>
            <th>Branch</th>
            <th>State</th>
            <th>City</th>
            <th>Distance (kilometers)</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @nearest_branches.zip(@nearest_distances).each do |branch, distance| %>
            <%@count=@count+1%>
            <tr>
              <td><%= @count %></td>
              <td><%= branch.name %></td>
              <%selectbranch = Branch.find_by(name:branch.name)%>
              <%city = City.find_by(id:selectbranch.city_id)%>
              <td><%= city.state %></td>
              <td><%= city.name %></td>
              <td><%= sprintf('%.2f', distance) %></td>
              <td> <a class="btn btn-primary" href="/branches/<%=selectbranch.id%>" target="blank">Details</a> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p class="h5 text-center text-danger">No nearest branches found.</p>
    <% end %>
  </div>
</div>

app/views/branches/index.html.erb
<div class="row">
  <div class="col-sm-3">
    <%= render 'dashboard/sidebar'%>
  </div>
  <div class="col-sm-9">
    <div class="row">
      <div class="col-sm-6 mt-3">
           <%= render partial:"shared/branch"%>
      </div>
      <div class="col-sm-5 mt-3 ms-5 ps-5">
        <div class="container">
          <form>
            <div class="mb-3">
              <label class="mb-3 h6">Add New Branch</label>
              <br>
              <label for="city-select" class="form-label">Select City:</label>
              <select id="city-select" class="form-select">
                <% @city.each do |city| %>
                  <option class="city-name-input" value="<%= city.id %>"><%= city.name %></option>
                <% end %>
              </select>
            </div>
            <div class="mb-3">
              <label for="branch-input" class="form-label">Enter Branch name:</label>
              <input type="text" id="branch-input" class="form-control required" placeholder="branch name">
            </div>
            <div class="mb-3">
              <label for="address-input" class="form-label">Enter Branch address:</label>
              <input type="text" id="address-input" class="form-control required" placeholder="mention locality, road, landmark, pin">
            </div>
            <div class="mb-3">
              <label for="maplink-input" class="form-label">Enter google map link:</label>
              <input type="text" id="maplink-input" class="form-control required" placeholder="map link">
            </div>
            <div class="mb-3">
              <label for="lat-input" class="form-label">Enter latitude of branch:</label>
              <input type="text" id="lat-input" class="form-control required" placeholder="latitude of branch ex: 2.3522219">
            </div>
            <div class="mb-3">
              <label for="long-input" class="form-label">Enter longitude of branch:</label>
              <input type="text" id="long-input" class="form-control required" placeholder="longitude of branch ex: 48.856614">
            </div>
            <button class="btn btn-primary" id="add-branch-btn">Add Branch</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'branch_index', 'data-turbolinks-track': 'reload' %>

app/views/branches/show.html.erb
<div class="row">
  <%if session[:role]=="admin"%>
    <div class="col-lg-3" style="width: 280px;height: 84vh;">
      <div class="d-flex flex-column flex-shrink-0 p-3 bg-light h-100" style="width: 280px;margin-top:-0.rem;">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
          <span class="fs-4">Admin Dashboard</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
          <li class="nav-item">
            <%=link_to "Users",users_path , class:"nav-link link-dark hover-effect"%>
          </li>
          <li>
            <%=link_to "City",cities_path , class:"nav-link link-dark hover-effect"%>
          </li>
          <li>
            <%=link_to "Brands",brands_path , class:"nav-link link-dark hover-effect"%>
          </li>
          <li>
            <%=link_to "Model",car_models_path , class:"nav-link link-dark hover-effect"%>
          </li>
          <li>
            <%=link_to "Appointment",root_path , class:"nav-link link-dark hover-effect"%>
          </li>
          <li>
            <%=link_to "Car Condition",set_car_condition_path , class:"nav-link link-dark hover-effect"%>
          </li>
          <li>
            <%=link_to "Branches",branches_path , class:"nav-link link-dark hover-effect"%>
          </li>
          <li>
            <%=link_to "Branch Details",branch_path(@branch), class:"nav-link active hover-effect"%>
          </li>
        </ul>
        <hr>
        <div class="dropdown">
          <a href="#" class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle me-2">
            <strong><%=current_user.name%></strong>
          </a>
          <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser2">
            <li><%=link_to "Profile",user_path(session[:user_id]),class:"dropdown-item"%></li>
            <li><%=link_to "Update Info",edit_user_path(session[:user_id]),class:"dropdown-item"%></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= button_to "Logout", session_path(session[:user_id]), class: "dropdown-item", method: :delete %></li>
          </ul>
        </div>
      </div>
    </div>
  <%end%>
  <div class="col-lg-4 ms-4">
    <div class="row">
      <div class="col-md-5 mt-3">
        <label class="mb-3 h6">Branch details</label>
        <div class="list-container" style="height: 400px;">
          <table class="table table-striped table-hover">
            <tbody>
              <tr>
                <th>Name</th>
                <td class="h6"><%=@branch.name%></td>
              </tr>
              <tr>
                <th>City</th>
                <td ><%=@city.name%></td>
              </tr>
              <tr>
                <th>State</th>
                <td ><%=@city.state%></td>
              </tr>
              <tr>
                <th>Detail Address</th>
                <td ><%=@branch.address%></td>
              </tr>
               <tr>
                <th>Map Link</th>
                <td > <a href="<%=@branch.map_link%>" target="blank"><%=@branch.map_link%></a> </td>
              </tr>
              <tr>
                <th>Latitude</th>
                <td ><%=@branch.latitude%></td>
              </tr>
              <tr>
                <th>Longitude</th>
                <td ><%=@branch.longitude%></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4 mt-3">
      <div class="row">
        <div class="h6 text-center mb-3">Branch Location on map</div>
        <div class="mapouter">
          <div class="gmap_canvas">
            <iframe width="80%" height="400px" id="gmap_canvas" src="https://maps.google.com/maps?q=<%= @branch.latitude %>,<%= @branch.longitude %>&t=&z=14&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
            <style>.mapouter{position:relative;text-align:right;height:100%;width:100%;}</style>
            <style>.gmap_canvas {overflow:hidden;background:none!important;height:100%;width:100%;}</style>
          </div>
        </div>
      </div>
  </div>
</div>