config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root 'home#welcome'
  get '/404', to: 'application#not_found'

  # session
  resources :sessions, only: %i[new create destroy]
  get 'login_verify', to: 'sessions#confirm_email'
  get 'resend_verification_link', to: 'sessions#getting_resend_verification_link'
  post 'resend_verification_link', to: 'sessions#resend_verification_link'

  # fogot_password
  get 'password_forget', to: 'password#new'
  post 'password_reset_link', to: 'password#reset_link'
  get 'password_reset', to: 'password#password_reset'
  post 'password_update', to: 'password#update'

  # user
  resources :users
  patch 'make_admin', to: 'users#make_admin'

  # city
  resources :cities

  # brand
  resources :brands, only: %i[index create update destroy]

  # car_model
  resources :car_models, only: %i[index create update destroy]

  # dashboard
  get 'admin_dashboard', to: 'dashboard#admin_dashboard'

  # branch
  resources :branches
  get 'find_nearest_branches', to: 'branches#all_branches'
  post 'getlocation', to: 'branches#getlocation'

  # car
  resources :cars, only: %i[new create index show]
  get 'set_car_condition', to: 'cars#set_condition'
  post 'set_car_condition/verify', to: 'cars#verify'

  # searching
  get 'search_cars', to: 'cars#search'
  # get 'filter_cars', to: 'cars#filter'

  # appointment
  post 'cars/inspection_request', to: 'appointment#request_from_seller'
  post 'buyer_dashboard/inspection_request', to: 'appointment#request_from_buyer'
  get 'appointments', to: 'appointment#all_appointments'
  get 'appointments/verification', to: 'appointment#all_appointments_in_admin_dashboard'
  post 'appointments/status_update/:id', to: 'appointment#status_update'
  get 'appointments/buyers_list/:id', to: 'appointment#buyers_list'
  post 'appointment/buyers_list/final_sell/:id/:sell_appointment', to: 'appointment#final_sell'
  post 'markread', to: 'appointment#markread'
  get 'find_status', to: 'appointment#status_check'
  post 'find_status', to: 'appointment#find_status'

  # filteration
  get 'appointment_filter', to: 'filteration#appointment_filter'
  get 'car_filter', to: 'filteration#car_filter'
  get 'filter_and_sort_general_user_appointment', to: 'filteration#filter_and_sort_general_user_appointment'

  match '*unmatched', to: 'application#not_found', layout: false, via: :all, constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage' # Exclude Active Storage routes
  }
end
# rubocop:enable Metrics/BlockLength

app/models/appointment.rb
# frozen_string_literal: true

# Appointment Model
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :car

  before_create :generate_appointment_id

  validates :date, :user_id, :car_id, presence: true
  validate :date_must_be_in_future
  validates :appointment_id, uniqueness: true

  enum seller_status: { Sell_Pending: 'Sell_Pending', Sell_Processing: 'Sell_Processing',
                        Sell_Investigating: 'Sell_Investigating', Ready_for_Sell: 'Ready_for_Sell',
                        Sold: 'Sold', Reject: 'Reject' }
  enum buyer_status: { Buy_Pending: 'Buy_Pending', Buy_Processing: 'Buy_Processing',
                       Buy_Investigating: 'Buy_Investigating', Ready_to_Buy: 'Ready_to_Buy',
                       Bought: 'Bought', Buy_Request_Cancelled: 'Buy_Request_Cancelled' }

  def date_must_be_in_future
    return if date.blank?

    errors.add(:date, 'must be a present or future date') if date < Date.today
  end

  private

  def generate_appointment_id
    user_id_part = user_id.to_s.rjust(2, '0')
    car_reg_no = car.reg_no
    car_id_part = car.id.to_s.rjust(2, '0')
    self.appointment_id = "#{user_id_part}#{car_reg_no}#{car_id_part}"
  end
end

app/controllers/appointment_controller.rb
# frozen_string_literal: true

# Appointment controller
# rubocop:disable Metrics/AbcSize
class AppointmentController < ApplicationController
  before_action :require_user
  before_action :require_admin, only: [:all_appointments_in_admin_dashboard]
  include AppointmentHelper
  include FilterationHelper
  def request_from_seller
    request_appointment_data
    appointment = Appointment.new(date: @date, user_id: @user_id,
                                  car_id: @car_id, status: 'Sell_Pending')
    if appointment.save
      update_selling_appointment_status(@car_id)
    else
      update_selling_appointment_status_failure
    end
  end

  def all_appointments
    @clear_filter = false
    @appointments = Appointment.where(user_id: session[:user_id])
  end

  def all_appointments_in_admin_dashboard
    @active_window = 'appointment'
    @appointments = Appointment.all
    default_sort_order(define_custom_order)
  end

  def status_update
    appointment = Appointment.find_by(id: params[:id])
    appointment.update(status: params[:status])
    CarsellingMailer.status_update(appointment.user, appointment).deliver_later

    notification_content = "Appoinment(#{appointment.appointment_id}) status has been updated to #{params[:status]}"
    notification = Notification.new(user_id: appointment.user_id, message: notification_content, status: false)
    send_notification(notification) if notification.save

    return unless appointment.user.role == 'seller'

    car = Car.find_by(reg_no: params[:reg_no])
    car.update(selling_appointment_status: params[:status])
  end

  def request_from_buyer
    request_appointment_data
    appointment = Appointment.new(date: @date, user_id: @user_id, car_id: @car_id, status: 'Buy_Pending')
    if appointment.save
      success_for_request_from_buyer
    else
      failure_for_request_from_buyer
    end
  end

  def buyers_list
    @appointment = Appointment.find_by(id: params[:id])
    @car = Car.find_by(id: @appointment.car_id)
    @appointments = Appointment.where(car_id: @car.id)
  end

  def final_sell
    fetch_params_for_final_sell
    car = Car.find_by(id: @seller_appointment.car.id)
    all_appoinments_with_same_car = Appointment.where(car_id: car.id)
    handle_all_appointments(all_appoinments_with_same_car, car, @seller_appointment, @appointment)
    flash[:success] = "Congratulations! Your car(#{car.reg_no}) has been sold successfully."
    redirect_to appointments_path
  end

  def markread
    user = params[:selected_btn]
    notifications = Notification.where(user_id: user)
    notifications.update(status: true)
  end

  def status_check; end

  def find_status
    id = params[:status_input]
    @show_template = false
    if valid_appointment_id(id)
      handle_valid_appointments_status_checking(id)
    else
      flash[:danger] = 'Invalid Appointment ID. Try again!'
      redirect_to find_status_path
    end
  end

  private

  def request_appointment_data
    @date = params[:appointmentDate]
    @car_id = params[:car_id]
    @user_id = session[:user_id]
  end

  def fetch_params_for_final_sell
    @appointment = Appointment.find_by(id: params[:id])
    @seller_appointment = Appointment.find_by(id: params[:sell_appointment])
  end

  def handle_all_appointments(all_appoinments_with_same_car, car, seller_appointment, appointment)
    all_appoinments_with_same_car.each do |app|
      if app.user.role == 'buyer' && app.id != appointment.id
        handle_cancelled_appointments(app)
      elsif app.user.role == 'buyer' && app.id == appointment.id
        handle_bought_appointments(app, seller_appointment, car, appointment)
      else
        handle_successfull_sell_appointment(app, seller_appointment, appointment)
      end
    end
  end
end
# rubocop:enable Metrics/AbcSize

app/helpers/appointment_helper.rb
# frozen_string_literal: true

# Appointment Helper
module AppointmentHelper
  def update_selling_appointment_status(car_id)
    car = Car.find_by(id: car_id)
    car.update(selling_appointment_status: 'Sell_Pending')
    flash[:success] = 'Appointment booked successfully.'
    redirect_to appointments_path
  end

  def update_selling_appointment_status_failure
    flash[:danger] = 'Error occured while booking appointment.You are suggested to pick future dates'
    redirect_to cars_path
  end

  def success_for_request_from_buyer
    flash[:success] = 'Appointment booked successfully'
    redirect_to appointments_path
  end

  def failure_for_request_from_buyer
    flash[:danger] = 'Error occured while booking appointment.You are suggested to pick future dates'
    redirect_to cars_path
  end

  def handle_cancelled_appointments(app)
    @rejected_appointment = Appointment.find_by(id: app.id)
    @rejected_appointment.update(status: 'Buy_Request_Cancelled')
    CarsellingMailer.cancel_sell(@rejected_appointment.user).deliver_later
    notification_content = "Appoinment(#{app.appointment_id}) status has been updated to 'Buy_Request_Cancelled"
    notification = Notification.new(user_id: @rejected_appointment.user.id, message: notification_content,
                                    status: false)
    send_notification(notification) if notification.save
  end

  def handle_bought_appointments(app, seller_appointment, car, appointment)
    @success_appointment = Appointment.find_by(id: app.id)
    @success_appointment.update(status: 'Bought')
    CarsellingMailer.final_buy(seller_appointment.user, car, appointment.user).deliver_later
    notification_content = "Appoinment(#{app.appointment_id}) status has been updated to 'Bought'"
    notification = Notification.new(user_id: @success_appointment.user.id, message: notification_content,
                                    status: false)
    send_notification(notification) if notification.save
  end

  def handle_successfull_sell_appointment(app, seller_appointment, appointment)
    @success_sell_appointment = Appointment.find_by(id: app.id)
    @success_sell_appointment.update(status: 'Sold')
    car_id = @success_sell_appointment.car_id
    car = Car.find_by(id: car_id)
    car.update(selling_appointment_status: 'Sold')
    CarsellingMailer.final_sell(seller_appointment.user, car, appointment.user).deliver_later
    notification_content = "Appoinment(#{app.appointment_id}) status has been updated to 'Sold'"
    notification = Notification.new(user_id: @success_sell_appointment.user.id, message: notification_content,
                                    status: false)
    send_notification(notification) if notification.save
  end

  def valid_appointment_id(id)
    Appointment.exists?(appointment_id: id)
  end

  def check_if_user_own_that_appointment(id)
    appointment = Appointment.find_by(appointment_id: id)
    appointment.user_id == session[:user_id]
  end

  def find_targeted_appointment(id)
    @appointment = Appointment.find_by(appointment_id: id)
  end

  def handle_successfull_appointment_status_finding(id)
    find_targeted_appointment(id)
    flash[:success] = 'Your appointment has been fetched Successfully'
    @show_template = true
  end

  def handle_valid_appointments_status_checking(id)
    if check_if_user_own_that_appointment(id)
      handle_successfull_appointment_status_finding(id)
    else
      flash[:danger] = "You are not allowed to check someone else's appointment status"
      redirect_to find_status_path
    end
  end

  def send_notification(notification)
    ActionCable.server.broadcast(
      "RoomChannel_#{notification.user_id}", {
        recipient_id: notification.user_id,
        message: notification.message
      }
    )
  end
end

app/views/appointment/_all_appointments_in_admin.html.erb
<div class="row">
  <div class="col-md-3 sidebar">
    <%= render 'dashboard/sidebar' %>
  </div>
  <div class="col-md-9 content">
    <div class="container">
      <div class="col-md-12 mb-3 mt-3">
        <%= form_with url: appointment_filter_path, method: :get, remote: true do %>
          <div class="row">
            <div class="col-md-2">
              <div class="form-inline">
                <label for="roleFilter" class="me-2">Filter by Role:</label>
                <%= select_tag 'role', options_for_select([['All', ''], ['Buyer', 'buyer'], ['Seller', 'seller']], params[:role]), class: 'form-select' %>
              </div>
            </div>
            <div class="col-md-3">
              <div class="form-inline">
                <label for="statusFilter" class="ms-4 me-2">Filter by Status:</label>
                <%= select_tag 'status', options_for_select([['All', ''], ['Pending', 'pending'], ['Processing', 'processing'], ['Investigating', 'investigating'], ['Ready for Sell/Buy', 'ready'], ['Sold/Bought', 'sold'], ['Reject/Request Cancel', 'reject']], params[:status]), class: 'form-select' %>
              </div>
            </div>
            <div class="col-md-3">
              <div class="form-inline">
                <label for="sortOption" class="ms-4 me-2">Sort by:</label>
                <%= select_tag 'sort_option', options_for_select([['Default', 'default'], ['Status (Ascending)', 'status-asc'], ['Status (Descending)', 'status-desc'], ['User Role (Ascending)', 'role-asc'], ['User Role (Descending)', 'role-desc'], ['Car Brand (Ascending)', 'car-brand-asc'], ['Car Brand (Descending)', 'car-brand-desc'], ['Car Model (Ascending)', 'car-model-asc'], ['Car Model (Descending)', 'car-model-desc'], ['Date Created (Newest First)', 'date-created-asc'], ['Date Created (Oldest First)', 'date-created-desc'], ['Appointment Date (Newest First)', 'appointment-date-asc'], ['Appointment Date (Oldest First)', 'appointment-date-desc']], params[:sort_option]), class: 'form-select' %>
              </div>
            </div>
            <div class="col-md-2 mt-4">
              <%= submit_tag 'Apply Filter and Sort', class: 'btn btn-primary' %>
            </div>
            <div class="col-md-2 mt-4">
              <% if @clear_filter%>
                <%= link_to "Clear Filter", appointments_verification_path, class: "ms-2 btn btn-danger"%>
              <%end%>
            </div>
          </div>
        <% end %>
      </div>
      <div class="row mt-4">
        <%= render 'appointment/appointment_card_in_admin_dashboard' %>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'appointment_in_admin_dashboard', 'data-turbolinks-track': 'reload' %>

app/views/appointment/_all_appointments_in_general_user.html.erb
<div class="ms-5 row">
  <div class="col-md-12 mb-3 mt-3">
    <% if session[:role] == 'buyer' && @clear_filter == false%>
    <%= link_to  "Back", cars_path %>
    <%end%>
    <% if session[:role] == 'seller' && @clear_filter == false%>
    <%= link_to  "Back", cars_path %>
    <%end%>
    <div class="row">
      <%= render 'appointment/appointment_filteration_for_users'%>
    </div>
  </div>
</div>
<div class="conatiner ps-2">
  <div class="row ms-5 me-5 mt-4 mb-3">
    <%@appointments.each do |app|%>
    <% if app.user.id == session[:user_id] %>
    <div class="card bg-light pb-2 me-4 mb-3" style="width: 18rem;" data-status="<%= app.status %>" data-car-brand="<%= app.car.brand.name %>" data-car-model="<%= app.car.car_model.name %>" data-created-date="<%= app.created_at.strftime('%Y%m%d%H%M%S') %>" data-appointment-date="<%= app.date.strftime('%Y%m%d%H%M%S') %>">
      <div class="card-body">
        <h5 class="card-title"> <%= app.car.brand.name %> - <%= app.car.car_model.name %></h5>
        <h6 class="card-title"> <%= app.car.reg_no %></h6>
        <h6 class="card-text">Appointment ID: <%= app.appointment_id %></h6>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Appointment Status: <strong><%= app.status %></strong></li>
        <li class="list-group-item">Appointment Date: <strong><%= app.date.strftime('%d %b, %Y') %></strong></li>
        <li class="list-group-item">Created At: <strong><%= app.created_at.localtime.strftime('%d %b, %Y, %l:%M %p') %></strong></li>
        <li class="list-group-item">Appointment Updated On: <br><strong><%= app.updated_at.localtime.strftime('%d %b, %Y, %l:%M %p') %></strong></li>
      </ul>
      <% if session[:role] == 'seller' %>
      <% if app.status == 'Ready_for_Sell' %>
      <a href="/appointments/buyers_list/<%= app.id %>" class="btn btn-outline-primary btn-sm mx-4 mt-2">See Buyer's List</a>
      <% else %>
      <button href="#" class="btn btn-outline-primary btn-sm mx-4 mt-2" disabled>See Buyer's List</button>
      <% end %>
      <% end %>
    </div>
    <% end %>
    <%end%>
    <% if @appointments == [] && @clear_filter == false%>
    <div class="alert alert-secondary h5 text-primary text-center" role="alert">
      You have not booked any appointments yet . Visit your dashboard to book appointments
    </div>
    <%end%>
    <% if @appointments == [] && @clear_filter == true%>
      <div class="alert alert-secondary h5 text-primary text-center" role="alert">
        No such record found . Try different filters and sorts
      </div>
    <%end%>
  </div>
</div>

app/views/appointment/_appointment_card_in_admin_dashboard.html.erb
<% @appointments.each do |app| %>
  <div class="card bg-light pb-4 me-4 mb-3" style="width: 18rem;"
    data-status="<%= app.status %>"
    data-role="<%= app.user.role %>"
    data-car-brand="<%= app.car.brand.name %>"
    data-car-model="<%= app.car.car_model.name %>"
    data-created-date="<%= app.created_at.localtime.strftime('%Y%m%d%H%M%S') %>"
    data-appointment-date="<%= app.date.strftime('%Y%m%d%H%M%S') %>">
    <div class="card-body">
      <h5 class="card-title"><%= app.car.brand.name %> - <%= app.car.car_model.name %></h5>
      <p class="card-text">Reg No: <span id="reg-no-<%= app.id %>"><%= app.car.reg_no %></span></p>
      <p class="card-text">Appointment Type: <%= app.user.role %></p>
      <p class="card-text">Appointment ID: <%= app.appointment_id %></p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Appointment asked for:<br><strong><%= app.date.strftime('%d %b, %Y')%></strong></li>
      <li class="list-group-item">Status: <strong id="appointment-status-<%= app.id %>"><%= app.status %></strong></li>
      <li class="list-group-item">Taken By: <strong id="appointment-made-by-<%= app.user_id %>"><%= app.user.name %></strong></li>
    </ul>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Appointment Created on:<br><strong><%= app.created_at.localtime.strftime('%d %b, %Y') %></strong></li>
      <li class="list-group-item">Appointment Updated on:<br><strong><%= app.updated_at.localtime.strftime('%d %b, %Y') %></strong></li>
    </ul>
    <div class="card-body">
      <select class="form-select" name="status" id="appointment-status-select-<%= app.id %>">
        <% if app.user.role == 'buyer' %>
        <% Appointment.buyer_statuses.each do |status, label| %>
        <option value="<%= status %>" <%= 'selected' if app.status == status %>>
          <%= label %>
        </option>
        <% end %>
        <% else %>
        <% Appointment.seller_statuses.each do |status, label| %>
        <option value="<%= status %>" <%= 'selected' if app.status == status %>>
          <%= label %>
        </option>
        <% end %>
        <% end %>
      </select>
      <button class="btn btn-primary mt-4" onclick="updateAppointmentStatus(<%= app.id %>)" data-appointment-id="<%= app.id %>">Make Changes</button>
    </div>
  </div>
<% end %>

app/views/appointment/_appointment_filteration_for_users.html.erb
<%= form_with  url: filter_and_sort_general_user_appointment_path, method: :get, remote: true, id: 'filter-sort-form' do |form|%>
<div class="row g-2 d-flex justify-content-between">
  <div class="col-sm-4">
      <%= form.label 'statusFilter', 'Filter by Status:', class: 'ms-4 me-2' %>
      <%= form.select 'statusFilter', options_for_select(
                                       {
                                         'All' => '',
                                         'Pending' => 'pending',
                                         'Processing' => 'processing',
                                         'Investigating' => 'investigating',
                                         session[:role] == 'buyer' ? 'Ready to Buy' : 'Ready for Sell' => 'ready',
                                         session[:role] == 'buyer' ? 'Bought' : 'Sold' => 'sold',
                                         session[:role] == 'buyer' ? 'Buy Request Cancelled' : 'Reject' => 'reject'
                                       },params[:statusFilter]), {class: "form-select", id: 'statusFilter'}%>
  </div>

  <div class="col-sm-4">
      <%= form.label 'sortOption', 'Sort by:', class: 'ms-4 me-2' %>
      <%= form.select 'sortOption', options_for_select(
                                    {
                                      'Default' => 'default',
                                      'Status (Ascending)' => 'status-asc',
                                      'Status (Descending)' => 'status-desc',
                                      'Car Brand (Ascending)' => 'car-brand-asc',
                                      'Car Brand (Descending)' => 'car-brand-desc',
                                      'Car Model (Ascending)' => 'car-model-asc',
                                      'Car Model (Descending)' => 'car-model-desc',
                                      'Date Created (Newest First)' => 'date-created-asc',
                                      'Date Created (Oldest First)' => 'date-created-desc',
                                      'Appointment Date (Newest First)' => 'appointment-date-asc',
                                      'Appointment Date (Oldest First)' => 'appointment-date-desc'
                                    },params[:sortOption]), class: 'form-select', id: 'sortOption' %>
  </div>

  <div class="col-sm-4 d-flex justify-content-center">
    <%= form.submit 'Apply filter and sort', class: 'btn btn-primary' ,id: 'apply-fiter-button-g'%>
    <% if @clear_filter %>
      <%= link_to "Clear filter and Sort", appointments_path, class:"btn btn-danger ms-2"%>
    <%end%>
  </div>
</div>
<% end %>

app/views/appointment/all_appointments.html.erb
<%= render 'all_appointments_in_general_user'%>

app/views/appointment/all_appointments_in_admin_dashboard.html.erb
<%= render 'all_appointments_in_admin' %>

app/views/appointment/buyers_list.html.erb
<div class="container-fluid mt-4 me-2 ms-2">
  <div class="row">
    <div class="col-lg-3">
      <p class="h6">Your appointment Details</p>
      <div class="card bg-light pb-2 mt-4" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"> <%=@appointment.car.brand.name%> - <%=@appointment.car.car_model.name%></h5>
          <h6 class="card-title"> <%=@appointment.car.reg_no%></h6>
          <p class="card-text"> <%=%> </p>
        </div>
        <ul class="list-group list-group-flush">
        <li class="list-group-item">appointment ID : <strong> <%=@appointment.appointment_id  %> </strong></li>
          <li class="list-group-item">appointment Status : <strong> <%=@appointment.status  %> </strong></li>
          <li class="list-group-item">appointment date : <strong> <%=@appointment.date%> </strong></li>
          <li class="list-group-item">Created at: <strong><%= @appointment.created_at.localtime.strftime('%d %b, %Y, %l:%M %p') %></strong></li>
          <li class="list-group-item">appointment Updated on: <br><strong><%= @appointment.updated_at.localtime.strftime('%d %b, %Y, %l:%M %p') %></strong></li>
        </ul>
      </div>
    </div>
    <div class="col-lg-3">
      <p class="h6 ms-3">Car Details</p>
      <div class="card ms-3 mb-4 mt-4" style="width: 18rem;background-color: #eee;">
        <div class="card-body">
          <h5 class="card-title"> <%=@car.brand.name%> <%= @car.car_model.name%></h5>
          <p class="card-text"> <%= @car.variant%>  <br> <%= @car.kilometer_driven%> kms</p>
          <p class="card-text"> Price : <%= @car.price.present? ? @car.price: "yet to update" %> </p>
          <p class="card-text">  Condition: <%= @car.condition.present? ? @car.condition: "yet to update" %> </p>
          <p> Available at : <br> <%= @car.branch.name%> <br> <%= @car.branch.city.name%> </p>
          <div class="d-flex flex-column">
            <a type="button" class="btn btn-primary flex-fill mb-2" target="blank" data-mdb-ripple-color="dark" href="/cars/<%=@car.id%>">
              view
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <p class="h6 ms-5">Interested Buyer's List</p>
      <div class="table-responsive ms-5 mt-4" style="width:30vw;">
        <table class="table">
          <thead>
            <tr>
              <th>Buyer's Name</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% if @appointments.empty? || (@appointments.size == 1 && @appointments.first.user.role == 'seller') %>
              <tr>
                <td colspan="2">No Buyers yet. Check after a few days.</td>
              </tr>
            <% else %>
              <% @appointments.each do |app| %>
                <% if app.user.role == 'buyer' && app.status == 'Ready_to_Buy' %>
                  <tr>
                    <td><%= app.user.name %></td>
                    <td class="d-flex flex-row">
                      <%= button_to "Sell", "/appointment/buyers_list/final_sell/#{app.id}/#{@appointment.id}", method: :post, class: "btn btn-primary btn-sm me-2"%>
                      <a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#buyerProfileModal<%= app.user.id %>">Buyer's Profile</a>
                    </td>
                  </tr>
                  <!-- Modal -->
                  <div class="modal fade" id="buyerProfileModal<%= app.user.id %>" tabindex="-1" aria-labelledby="buyerProfileModalLabel<%= app.user.id %>" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="buyerProfileModalLabel<%= app.user.id %>">Buyer's Profile</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                          <p>Buyer's Name: <%= app.user.name %></p>
                          <p>Buyer's Email: <%= app.user.email %></p>
                          <p>Buyer's Mobile Number: <%= app.user.mobile_no %></p>
                          <p>Buyer's verification completed on : <%= app.updated_at.localtime.strftime('%d %b, %Y, %l:%M %p')%></p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/appointment/find_status.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-lg-3">
      <%= form_tag(find_status_path, method: :post) do %>
        <div class="form-group">
          <%= label_tag :status_input, "Enter Appointment ID to know status",class: "mb-2" %>
          <%= text_field_tag :status_input, nil, class: "form-control" %>
        </div>
        <%= submit_tag "Check Status", class: "btn btn-primary mt-4" %>
      <% end %>
    </div>
  <% if @show_template%>
    <div class="col-lg-3">
      <table class="table">
        <tr>
          <th>Appointment Status:</th>
        </tr>
        <tr>
          <td><strong><%= @appointment.status %></strong></td>
        </tr>
      </table>
    </div>
    <div class="col-lg-4">
      <div class="card bg-light pb-2 me-4 mb-3" style="width: 18rem;" data-status="<%= @appointment.status %>" data-car-brand="<%= @appointment.car.brand.name %>" data-car-model="<%= @appointment.car.car_model.name %>" data-created-date="<%= @appointment.created_at.strftime('%Y%m%d%H%M%S') %>" data-appointment-date="<%= @appointment.date.strftime('%Y%m%d%H%M%S') %>">
        <div class="card-body">
          <h5 class="card-title"> <%= @appointment.car.brand.name %> - <%= @appointment.car.car_model.name %></h5>
          <h6 class="card-title"> <%= @appointment.car.reg_no %></h6>
          <h6 class="card-text">Appointment ID: <%= @appointment.appointment_id %></h6>
        </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Appointment Status: <strong><%= @appointment.status %></strong></li>
        <li class="list-group-item">Appointment Date: <strong><%= @appointment.date.strftime('%d %b, %Y') %></strong></li>
        <li class="list-group-item">Created At: <strong><%= @appointment.created_at.localtime.strftime('%d %b, %Y, %l:%M %p') %></strong></li>
        <li class="list-group-item">Appointment Updated On: <br><strong><%= @appointment.updated_at.localtime.strftime('%d %b, %Y, %l:%M %p') %></strong></li>
      </ul>
      </div>
    </div>
  <%end%>
  </div>
</div>

app/views/appointment/status_check.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-lg-4">
      <%= form_tag(find_status_path, method: :post) do %>
        <div class="form-group">
          <%= label_tag :status_input, "Enter Appointment ID to know status",class: "mb-2" %>
          <%= text_field_tag :status_input, nil, class: "form-control" %>
        </div>
        <%= submit_tag "Check Status", class: "btn btn-primary mt-4" %>
      <% end %>
    </div>
  </div>
</div>