config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root 'home#welcome'
  get '/404', to: 'application#not_found'

  # session
  resources :sessions, only: %i[new create destroy]
  get 'login_verify', to: 'sessions#confirm_email'
  get 'resend_verification_link', to: 'sessions#getting_resend_verification_link'
  post 'resend_verification_link', to: 'sessions#resend_verification_link'

  # fogot_password
  get 'password_forget', to: 'password#new'
  post 'password_reset_link', to: 'password#reset_link'
  get 'password_reset', to: 'password#password_reset'
  post 'password_update', to: 'password#update'

  # user
  resources :users
  patch 'make_admin', to: 'users#make_admin'

  # city
  resources :cities

  # brand
  resources :brands, only: %i[index create update destroy]

  # car_model
  resources :car_models, only: %i[index create update destroy]

  # dashboard
  get 'admin_dashboard', to: 'dashboard#admin_dashboard'

  # branch
  resources :branches
  get 'find_nearest_branches', to: 'branches#all_branches'
  post 'getlocation', to: 'branches#getlocation'

  # car
  resources :cars, only: %i[new create index show]
  get 'set_car_condition', to: 'cars#set_condition'
  post 'set_car_condition/verify', to: 'cars#verify'

  # searching
  get 'search_cars', to: 'cars#search'
  # get 'filter_cars', to: 'cars#filter'

  # appointment
  post 'cars/inspection_request', to: 'appointment#request_from_seller'
  post 'buyer_dashboard/inspection_request', to: 'appointment#request_from_buyer'
  get 'appointments', to: 'appointment#all_appointments'
  get 'appointments/verification', to: 'appointment#all_appointments_in_admin_dashboard'
  post 'appointments/status_update/:id', to: 'appointment#status_update'
  get 'appointments/buyers_list/:id', to: 'appointment#buyers_list'
  post 'appointment/buyers_list/final_sell/:id/:sell_appointment', to: 'appointment#final_sell'
  post 'markread', to: 'appointment#markread'
  get 'find_status', to: 'appointment#status_check'
  post 'find_status', to: 'appointment#find_status'

  # filteration
  get 'appointment_filter', to: 'filteration#appointment_filter'
  get 'car_filter', to: 'filteration#car_filter'
  get 'filter_and_sort_general_user_appointment', to: 'filteration#filter_and_sort_general_user_appointment'

  match '*unmatched', to: 'application#not_found', layout: false, via: :all, constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage' # Exclude Active Storage routes
  }
end
# rubocop:enable Metrics/BlockLength

app/views/shared/_branch.html.erb
<label class="mb-3 h6">List of already available Branches</label>
<div class="list-container" style="height: 500px;">
  <div class="list-content">
    <ul class="list-group" id="model-list">
      <% @branch.each do |branch| %>
      <% city_name = City.find_by(id: branch.city_id) %>
        <div class="d-flex row list-group-item">
          <div class="col-sm-7"> <li class=""><%= branch.name %> ( <%= city_name.name %> )</div>
          <div class="col-sm-3 d-flex">
            <a class="btn btn-primary" href="branches/<%= branch.id %>" role="button" target="_blank">Details</a>
            <% if session[:role] == 'admin'%>
              <a class="btn btn-info ms-2" href="branches/<%= branch.id %>/edit" role="button">Edit</a>
              <a class="btn btn-danger ms-2" href="branches/<%= branch.id %>" role="button" data-method="delete" data-confirm="Are you sure you want to delete this branch?">Delete</a>
            <%end%>
          </div>
        </div>
      </li>
      <% end %>
    </ul>
   </div>
</div>

app/views/shared/_flash.html.erb
<div class="container-fluid flash">
  <% flash.each do |type, msg| %>
  <div class="alert alert-<%=type%> text-center" id="flash" role="alert">
    <strong> <%= msg %> </strong>
  </div>
  <script>
    function remove_flash(){
      $(document).ready(function(){
        setTimeout(function(){

          $('#flash').fadeOut();
        }, 3000);
      })
    }
    remove_flash()
  </script>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light ">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
    <span class="text-danger font-weight-bold h4">S</span><span class="text-warning font-weight-bold h4">e</span><span class="text-success font-weight-bold h4">c</span><span class="text-primary font-weight-bold h4">o</span><span class="text-danger font-weight-bold h4">n</span><span class="text-warning font-weight-bold h4">d</span> <span class="text-danger font-weight-bold h4">W</span><span class="text-success font-weight-bold h4">h</span><span class="text-warning font-weight-bold h4">e</span><span class="text-primary font-weight-bold h4">e</span><span class="text-danger font-weight-bold h4">l</span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%=link_to "Home",root_path,class:"nav-link",aria_current:"page"%>
        </li>
        <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          My account
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%if session[:role] != 'admin'%>
            <li><a class="dropdown-item" href="/appointments">My appointment</a></li>
            <li><a class="dropdown-item" href="/find_status">Status</a></li>
            <%end%>
            <li><%=link_to "My profile",user_path(session[:user_id]),class:"dropdown-item"%></li>
          </ul>
        </li>
        <% end %>
        <%if logged_in? && session[:role] == 'buyer'%>
        <li class="nav-item">
          <%=link_to "My Dashboard",cars_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%=link_to "Branch",find_nearest_branches_path  ,class:"nav-link "%>
        </li>
        <%elsif logged_in? && session[:role] == 'seller'%>
        <li class="nav-item">
          <%=link_to "My Dashboard",cars_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%=link_to "Sell car",new_car_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%=link_to "Branch",find_nearest_branches_path,class:"nav-link "%>
        </li>
        <%elsif logged_in? && session[:role] == 'admin'%>
        <li class="nav-item">
          <%=link_to "My Dashboard",admin_dashboard_path,class:"nav-link"%>
        </li>
        <% end %>
      </ul>
      <% if !logged_in? %>
      <div class="d-flex">
        <%= link_to "Signup", new_user_path, class: "btn btn-primary" %>
        <%= link_to "Login", new_session_path, class: "btn btn-info ms-2" %>
      </div>
      <% else %>
      <div class="notification me-3">
        <div class="dropdown">
          <a class="btn btn-success dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
          <% if logged_in? && notification_count > 0 %>
          <i class="fa-regular fa-bell"></i>
          <span id="notification-count" class="badge rounded-pill badge-notification bg-warning ms-1" data-count="<%= notification_count %>">
          <%= notification_count %>
          </span>
          <% else %>
          <i class="fa-regular fa-bell"></i>
          <span id="notification-count" class="badge rounded-pill badge-notification bg-warning ms-1" data-count="0">0</span>
          <% end %>
          </a>
          <% if logged_in? && notification_count>0%>
          <ul class="dropdown-menu" style="width:auto;height:auto;overflow:auto" id="notification-list" aria-labelledby="dropdownMenuButton1">
            <button class="btn btn-sm btn-primary mark-read ms-1" value="<%= current_user.id %>" id="readbtn">Mark all as read</button>
            <% unread_notifications.each do |notification| %>
            <li class="notification-message ms-2 me-2 mt-3"><%= notification.message %></li>
            <% end %>
          </ul>
          <% elsif logged_in? && notification_count == 0%>
          <ul class="dropdown-menu" style="width:auto;height:auto;overflow:auto" id="notification-list" aria-labelledby="dropdownMenuButton1">
            <button class="btn btn-sm btn-primary mark-read" value="<%= current_user.id %>" id="readbtn">Mark all as read</button>
            <li class="notification-message ps-2" id="no-notification">No Notification Yet</li>
          </ul>
          <% end %>
        </div>
      </div>
      <div class="d-flex">
        <p class="mt-2">Welcome, <%= current_user.name %> - <%= current_user.role %></p>
        <%= button_to "Log Out", session_path(session[:user_id]), class: "btn btn-danger ms-2 me-2",method: :delete, data: { confirm: "Are you sure you want to log out?" }%>
      </div>
      <% end %>
    </div>
  </div>
</nav>
<%= javascript_pack_tag 'readnotification', 'data-turbolinks-track': 'reload' %>